--Rishabh Nigam 103607336
-- EVENT (EventYear, EventMonth, EventDay)
-- PRIMARY KEY (EventYear, EventMonth,EventDay)
-- FOREIGN KEY (FEE) REFERENCES COST

-- BOOKING (DateBooked, Payment)
-- PRIMARY KEY (DateBooked, Payment)

-- CLIENT (ClientID, Surname, GivenName, Gender)
-- PRIMARY KEY (ClientID)
-- FOREIGN KEY (Surname, GivenName, Gender)

-- TOUR (TourName, Descriotion)
-- PRIMARY KEY (TourName)
-- FOREIGN KEY Descriotion

